### ISSUE TITLE
Periodically pin images from https://dap.ps/

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-ipfs#2]
We need some kind of automation to pin images submitted for dapps on https://dap.ps/
```
 $ curl -s https://dap.ps/metadata/all | jq -r '.[].details.image' | head
/metadata/image/QmbKeFJpV2fj4hpF9PuGFtfC4uNouCHMBrCzjuv5atB7BF
/metadata/image/QmbKeFJpV2fj4hpF9PuGFtfC4uNouCHMBrCzjuv5atB7BF
/metadata/image/QmeARp1QCj4k15N5HDDK4GPkgn1TyLdtCbngJfFh9AY4Sa
/metadata/image/QmSCJNNdEh1nKN45y9b86ojp9idXzZaG2o7FTWFvoYnvFN
/metadata/image/Qma4TLstcidGx3HCw26QkSayk4c6BK1Jz7yE2Lssp4mjQa
/metadata/image/QmdH5nRxFizQN1FYA1HzvEDgWQna8931oaQTszQmtwVgzN
/metadata/image/Qmaq1Th6GqEQF88Y28k39CshyTKxQUpGqH5ZqXa44nX5Yd
/metadata/image/QmaNBQX9BS5bA1d5KXnknC3KUeeoiuv1Xwg3LbzCxrMEwp
/metadata/image/QmXqjkVZJLGzWyV6swFtBtR1ViqRK2BA4oke13xV92bJJP
/metadata/image/QmbJGZJFogNTksVc5cuDX9LwfkzKh6KZSf8A1XJzyuhrFc
```

**Comment by jakubgs** [comment]
I already have an example of how to do this here:
https://github.com/status-im/infra-utils/blob/master/ipfs/pin_sticker_packs.py
I just need to find a way to generalize this so it can handle more than just this specific resource.

**Comment by jakubgs** [comment]
I'm a bit confused because I'm checking this MakerDai icon:
https://dap.ps/metadata/image/QmQjwMYddNsMX3MGkhgJ9eLwRB9bxzJoFkTHfGqMaMnfRX
But it doesn't seem to load on any gateways I try it with:
* https://ipfs.io/ipfs/QmVNtJfmeUTrzFMURL4rTNG7srz2cG2Ki4Mhxsi9qZa76g
* https://gateway.ipfs.io/ipfs/QmVNtJfmeUTrzFMURL4rTNG7srz2cG2Ki4Mhxsi9qZa76g
* https://ipfs.infura.io/ipfs/QmVNtJfmeUTrzFMURL4rTNG7srz2cG2Ki4Mhxsi9qZa76g
* https://hardbin.com/ipfs/QmVNtJfmeUTrzFMURL4rTNG7srz2cG2Ki4Mhxsi9qZa76g
* https://test-ipfs.status.im/ipfs/QmVNtJfmeUTrzFMURL4rTNG7srz2cG2Ki4Mhxsi9qZa76g

All I get are `504 Gateway Timeout` errors.

So pinning this results in very long `PINNING` state:
```
 $ d exec -it ipfs-cluster ipfs-cluster-ctl pin add QmQjwMYddNsMX3MGkhgJ9eLwRB9bxzJoFkTHfGqMaMnfRX
QmQjwMYddNsMX3MGkhgJ9eLwRB9bxzJoFkTHfGqMaMnfRX :
    > 4e1eb7bfc5af    : PINNING | 2020-01-14T20:19:00.959949884Z
    > c5d646d81193    : PINNING | 2020-01-14T20:19:01.021272419Z

 $ exec -it ipfs-cluster ipfs-cluster-ctl status QmQjwMYddNsMX3MGkhgJ9eLwRB9bxzJoFkTHfGqMaMnfRX
QmQjwMYddNsMX3MGkhgJ9eLwRB9bxzJoFkTHfGqMaMnfRX :
    > 4e1eb7bfc5af    : PINNING | 2020-01-14T20:19:00.959949884Z
    > c5d646d81193    : PINNING | 2020-01-14T20:19:01.021272419Z
```

**Comment by jakubgs** [comment]
Most attempts are forever stuck in `PINNING`:
```
$ ipfs-cluster ipfs-cluster-ctl status QmQjwMYddNsMX3MGkhgJ9eLwRB9bxzJoFkTHfGqMaMnfRX
QmQjwMYddNsMX3MGkhgJ9eLwRB9bxzJoFkTHfGqMaMnfRX :
    > 4e1eb7bfc5af    : PINNING | 2020-01-14T20:19:00.959949884Z
    > c5d646d81193    : PINNING | 2020-01-14T20:19:01.021272419Z
```
Or `PIN_QUEUED`:
```
$ ipfs-cluster ipfs-cluster-ctl status QmQpspDsX8hswA8yLkDyAzN6aQdVTpnhRE7m4bCEXNPoNK
QmQpspDsX8hswA8yLkDyAzN6aQdVTpnhRE7m4bCEXNPoNK :
    > 4e1eb7bfc5af    : PIN_QUEUED | 2020-01-14T20:27:32.910227611Z
    > c5d646d81193    : PIN_QUEUED | 2020-01-14T20:27:32.989854248Z
```
Which makes me think that those are not really available under IPFS at all.

**Comment by jakubgs** [comment]
@andytudhope found something:
```js
// Todo: pin the hash. Infura does not support it.
const contentHash = await this.storage.add(Buffer.from(JSON.stringify(content)));
logger.info(`Content ${content} was successfully uploaded in IPFS`);
```
https://github.com/dap-ps/discover/blob/master/back-end/services/ipfs-service.js#L21

Seems like the pinning of IPFS content was never done since Infura doesn't support it, so images were uploaded, but never pinned, and now they appear to be gone. Though they are available through caches.

**Comment by jakubgs** [comment]
I tried uploading the Maker logo through our own cluster and got a different hash than on the site:
http://ipfs.io/ipfs/QmTVWj2EVTbqXmAW7jtCH7e1o15SWk3YFiQRgVqomAzDAB
The one on the site is:
https://ipfs.io/ipfs/QmVNtJfmeUTrzFMURL4rTNG7srz2cG2Ki4Mhxsi9qZa76g

**Comment by jakubgs** [comment]
I think what we need to do is:

0. Rename https://test-ipfs.status.im/ to https://ipfs.status.im/
1. Download all the images
2. Re-upload them on our cluster at https://ipfs.status.im/
3. Update MongoDB with new IPFS hashes
4. Fix pinning of images in the [discover](https://github.com/dap-ps/discover) codebase

I will start on the 0.

**Comment by jakubgs** [comment]
Okay, I renamed the IPFS gateway to https://ipfs.status.im/ in https://github.com/status-im/infra-ipfs/issues/3.

Now I'm working on a simple utility for pinning content hashes from a file or STDIN.

**Comment by jakubgs** [comment]
Here's the first version of the script added in a8f6da8de63a65fc99bac55d86bbc0e9faee9d36:
https://github.com/status-im/infra-ipfs/blob/a8f6da8d/ansible/roles/ipfs-pinner/files/ipfs_pinner.py

**Comment by jakubgs** [comment]
I downloaded all the images using this shell command:
```
 $ curl -s https://dap.ps/metadata/all \
      | jq -r '.[].details.image' | sort | uniq \
      | xargs -L1 -I{} wget -q "https://dap.ps{}" 
 $ ls -l | head -n 4
total 1128
-rw-r--r-- 1 sochan sochan 10168 Jan 16 14:34 Qma2NyFRLZUeDukey4DBonCJmjbhtpwM2YdfqAaraPYirE
-rw-r--r-- 1 sochan sochan 35226 Jan 16 14:34 Qma4PcEYTC57Yo2VkX3nAT9fp62JHEr9HQNfZG21DE9zVa
-rw-r--r-- 1 sochan sochan  1875 Jan 16 14:34 Qma4TLstcidGx3HCw26QkSayk4c6BK1Jz7yE2Lssp4mjQa
```
Based on output from `file` utility I think all of them are PNG images.

**Comment by jakubgs** [comment]
I added the images by putting the `dap_images` under `/docker/ipfs-cluster/data` and running:
```
 $ ls | xargs -L1 -I{} docker exec -i ipfs-cluster ipfs-cluster-ctl add "/data/ipfs-cluster/dap_images/{}"
```
All the hashes I got back were different. Some examples:
```
added QmWzhXHkJqbqpBr6MQrG7P9kbsooFXgZcLKFTdeCE1NfmE QmNNw33HdK9UvyyKFHm1tboUgAQAYia8zGcXTa3bSFDteq.png
added QmYwRKzbSiSniMfCCBFJW1DLFiXwsBu492VNLAtCNajJj2 QmNWqSFiyHVuTseUAhJFYd3d84A8QcHw3yKFcqMsuTwLcR.png
added QmTAJQyNTHcU7yVJbh4bq5on1nspqcKGmrAMa2fAivZkQD QmPLDnznWSK3pGqe5ciNfNgc3dj2MbxvRneznaQ87HB8d1.png
added QmTq53kvbjNYr2mJw2dWh61R2yQ4R3LRtQFvaDi4e2CJvi QmPPfkqtzMNmKMjQcTkCEUwRSinkWnZR43rusAow8NLHrr.png
added QmVH4AQrxkBJi23noWFXdqLSQvLwuhXDgfwcFjPeUG18bx QmPdudGXQ8mjuVnxRWEKskP6BT3tHtDF8StTrwK8dhELHu.png
added QmQjmwntquhpaHwgv3hBXCk1PSy2kcP7XjvPfeCzJGY3R8 QmPp5M8YMntc3wkvDnSkeb8bht2wWowzaoNeSnyXjQhE6X.png
```

**Comment by jakubgs** [comment]
They are all pinned now:
```
admin@node-01.gc-us-central1-a.ipfs.prod:/docker/ipfs-cluster/data/dap_images % docker exec -it ipfs-cluster \
    ipfs-cluster-ctl pin ls QmWzhXHkJqbqpBr6MQrG7P9kbsooFXgZcLKFTdeCE1NfmE
QmWzhXHkJqbqpBr6MQrG7P9kbsooFXgZcLKFTdeCE1NfmE |  | PIN | Repl. Factor: -1 | Allocations: [everywhere] | Recursive | Metadata: no
```

**Comment by andytudhope** [comment]
This is awesome @jakubgs :heart: 

It's not only images we pin in IPFS though, it's also the whole DApp object, the hash of which is also stored in the contract. This has worked for most DApps that have staked SNT, though it seems there are 3 or 4 for which the pinning has failed. You can see a successful one here:

https://ipfs.io/ipfs/QmUmp9WaFYqD1Wh5aBLVUqD4QpqgPPzNN3hohuMu5WypE8

So, unlike the images, the hashing of the DApps is working well. However, some pins are not resolvable, so it would be awesome if we could use our cluster to pin these too. Any chance you could expand the scope here slightly?

**Comment by jakubgs** [comment]
I can take a look. But first I'll do the images.

**Comment by jakubgs** [comment]
I prepared a PR that makes it upload to our IPFS cluster and fixed some stuff: https://github.com/dap-ps/discover/pull/72
It was uploading images incorrectly, which is why the hashes were different compared to when I uploaded the images to our own cluster.

Almost as if someone incompetent wrote the backend to this service....

**Comment by jakubgs** [comment]
I uploaded the `dev.dap.ps` images to our IPFS cluster and hare are the changed hashes:
```json
{
  "QmQEtyC56XJxKc9c29F2Are1Htz3YN4oi4NKwPVzjHaDHu": "QmQXFZdCFfFqgdBn5NNHKGqNxHjzrb6tYsrUWmrh752oSr",
  "QmQWR7iGfjSiVonaqMkmR7UoDAX415CsEpptCQRd7MFRVZ": "QmePtJ1Vn82H4RM2LUUNGVqd5TgfSLJE33mYyYKHTPr6Xy",
  "QmRRPqUyA8nAwx6PVf3c8MemQS2JNpgxBknaG11h7EXdNU": "Qmd6jv3UkdmKZ5DsSMfxdKekij6UfPYetrB9ng4ememx1g",
  "QmRbPVvsXWZqLLPhP4PJPLZiZ7TLFXYjwrFZQUJb61AjkY": "QmRzGktYRK2PMPuvFDPyKg6Mnay1JCNmHp8BqDZkQuQHL9",
  "QmSdj3SV6HPjr8dC6Y3dFoHWhejHacTbAFtkcbA81BXjXA": "QmSdj3SV6HPjr8dC6Y3dFoHWhejHacTbAFtkcbA81BXjXA",
  "QmTVNzQh9cfE5gEdfFp2tZhTvQa2PaBpzoqxTncDQpackH": "QmVDCmbvoHzSNEMuyzhubGdKrpTccKELzeWS1XRQiPMk1b",
  "QmTXDJPDkDY8FKPEK9LTc72MW2Wfzt7amWYaonetqh6K1Z": "QmbTtyymgPat5hSYCs14aVYprMcimHXEZD9C7kPLvuLqmo",
  "QmTshaYkduDz7eQ2t5qvZMnS2QLnadhyqyRCc2E4gr7ur8": "Qmb24Sa3rkDHDKeyQXgivJUCsNCgTsQb5bGcUoUYLjDRS3",
  "QmUNhcMGY2tSYLpaXwzndYhF16enDymsGKY3KHBpxzDS1t": "QmSWhhE6GWep83pUhM92W6mNZdMH6M8gutjVcD9MDGeyXt",
  "QmUVHtdVr21xYMPey6bCZbVUoXcH5Y2Et19YShyPW9ofqP": "QmWq3eEeRTFTk1oqyuvioUpa6GTZ9zF8w9qzvsyqxuKCuC",
  "QmV2rcW76vy9GWYNtSfvvkf3fDiq4zHH1h72fxYUVUMBvT": "QmPJxKmckBKB5Yykw8GjHpnteC2t2xdt5VtK6Nm3K36ZZF",
  "QmVEJJYbNCUbkuSXWEfNZS854mqH4x7fa11Eq6vpzW1XA3": "QmWkZd2uPTNsoe6ZRRpGDxHHKWpox7tEx3pqJNvVsAdF7W",
  "QmWhWApTqoW2RzDcAjbDZcUzgrMMkHRLpraYTBD9Ajrxrj": "QmSgrLon5WKEqnaHSuzUR1JQNFeZ6wQLjt1WsCbZ4dQ4Jb",
  "QmWtuzbXxYEDknDHnbHRtnMP22h5HTtjhudEqwWmq3BkPJ": "QmTaL29uiDp2vyroxUQNqAwFdnff3RYnavgoKEzQk33LRP",
  "QmXmdsaXgnT6GD14TZtjEn3H9wfoQb8wyuvYtZ8gfuno83": "QmQPbRfYvmvCFbDPFeAWALeiEsyoUKCELCn16XdXNCSpTd",
  "QmXqDzN3nuA738F3VwfJwrQCgFJXx2FnRVwwGpatgq1qXG": "QmdLqfd7C1roSpSU1qagQbRpPPWFgCTSNdGbnityyyUh95",
  "QmXqG8cRjPLFt6Rf2dNqNEdNcj2q9HFA2Mz1hdrrfzBNXj": "QmbZcZf6yKsaAyk2gJu7BA1K7vosDzrERggEk2ZQnpLxUm",
  "QmYUQUsCLrr2nfbyt2JKDNPsriDjEdX797PUsFdibAuL5s": "QmZMqVPmhXHM7TVHWiRcQc9E1WJ5PMKkvCkaVNabsG6Sq6",
  "QmZhTrvs4yJejcywp1gPenZW2g9LuMk8xXi2XwXTtDULgF": "QmbbSvGPsNPcmyuW1wVRu5rR44MW7Ceivu54PFHDSMqR7q",
  "QmarycyUjwApQ964vzxKfXg3WE7KRBXR9UFd2gmJ3dDMGn": "QmZnFa7rXpsfATbG9195qccj1UnmYEEnysu4wXVQ1phfky",
  "QmbKeFJpV2fj4hpF9PuGFtfC4uNouCHMBrCzjuv5atB7BF": "QmV7iELRSYDTmtdkb8WB1XLGT2Bz1YbhqLCg7Mh7UMiXcs",
  "Qmbif3KaWidXu8mgeZELaH6qYLqd25aeAVBy3WVZYuTGtc": "QmayTmQsGQXNNjNG3Gw8ECzK6DvrhPYPEZPUush2Wf3Crc",
  "QmcGekjiqg86Awyz6TtS5viaXEan2NWPeD2bRqF4N4EiUh": "Qmf52qvWGTFXm8BDAxWo9XuqfT9Lpa1L3fp3SaebBnyv5x",
  "QmcNx4qFY9dxhntxJmF3EUBEtseJAy5ANMpVNDAqwigdn5": "QmWrGR9NfKscKYxBfwg3R2ehajSaRs3u5MLTwc2c794JDU",
  "QmdQgLx5thGRoR8HMu6hhrHprHUzUEJsKLhw3C6ktjwDPD": "QmZ6uh2Fqgc1WKGwsszmGVngXBm6dz6C5XwvUjeKMm4NUv",
  "QmeCTFBLECtyiZA9Wyh1VEGfSTQhjSmQRyRiEcvzCmT6iz": "QmaYDT3ztVVZ3KRJXFCtkENw18waXnwpfCQZUa8Tk38wMG",
  "QmeXp7FR7FSCKq2TVvXuhkqXbcsatZUM49JptuJXBrJ9zB": "QmeXp7FR7FSCKq2TVvXuhkqXbcsatZUM49JptuJXBrJ9zB",
  "QmeYUhvW3WmVFcFynwUvMTjDg12WeeHU9PiLVGwLxy4oqK": "QmQVMHbpFfirr1UyYeE5Fzv6gtomguFHsBiAMpz5gsM4Kx",
  "QmegVueHkeVu9PwuSG9fyu9N2c6cDUH1HnkqV8DNWNrDTn": "QmSBvn378uVfVXhG9ThqLZUYfXg2USbjdG2FWSfsoFER9H",
  "QmepPQ4J6aB6BX2LmgMdYLxH7oCk7VPC4MSYdao2oAJ8oG": "QmbPps3Gp7eWpofyRZ5CY41QGuNV6pGH3beGFBL9dkdu53",
  "Qmf3S91QDeTwVKRsf5dqH3mxsVoQcy1jFPY4y4Khf8XFkv": "QmQ3aSpL2XUaunHQ2yqivUVRXzKHyeQTk7LHqZPGkmjCEo",
  "QmfZp8gzRrGHTPPXbCGWcjJiFmHpGjSzQWzm3iUKYWAUzY": "QmViafYS4UBkE53JAW9S3g2B5Dfw7RoRYaj6TK5B1Bef8p"
}
```
I've used that data to Update the Dapp meatadata in MongoDB:
```
> d = { DATA_ABOVE }
> for (let hash in d) { print(db.dappsmetadatas.update({"details.image": "/metadata/image/"+hash}, {"$set":{"details":{"image":"/metadata/image/"+d[hash]}}})) }
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
...
```
And then updated the images themselves:
```
> for (let hash in d) { db.dappsimages.update({"hash": hash}, {"$set":{"hash": d[hash]}}); }
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
...
```
Now all the response from `/metadata/all` should be using correct hashes.

**Comment by jakubgs** [comment]
Looks good to me:
```
 $ curl -s https://dev.dap.ps/metadata/all | jq -r '.[].details.image' | sed -e 's#/metadata/image/#https://ipfs.status.im/#' 
```
- https://ipfs.status.im/QmaYDT3ztVVZ3KRJXFCtkENw18waXnwpfCQZUa8Tk38wMG
- https://ipfs.status.im/QmayTmQsGQXNNjNG3Gw8ECzK6DvrhPYPEZPUush2Wf3Crc
- https://ipfs.status.im/Qmb24Sa3rkDHDKeyQXgivJUCsNCgTsQb5bGcUoUYLjDRS3
- https://ipfs.status.im/QmbbSvGPsNPcmyuW1wVRu5rR44MW7Ceivu54PFHDSMqR7q
- https://ipfs.status.im/QmbPps3Gp7eWpofyRZ5CY41QGuNV6pGH3beGFBL9dkdu53
- https://ipfs.status.im/QmbTtyymgPat5hSYCs14aVYprMcimHXEZD9C7kPLvuLqmo
- https://ipfs.status.im/QmbZcZf6yKsaAyk2gJu7BA1K7vosDzrERggEk2ZQnpLxUm
- https://ipfs.status.im/Qmd6jv3UkdmKZ5DsSMfxdKekij6UfPYetrB9ng4ememx1g
- https://ipfs.status.im/QmdLqfd7C1roSpSU1qagQbRpPPWFgCTSNdGbnityyyUh95
- https://ipfs.status.im/QmeCTFBLECtyiZA9Wyh1VEGfSTQhjSmQRyRiEcvzCmT6iz
- https://ipfs.status.im/QmePtJ1Vn82H4RM2LUUNGVqd5TgfSLJE33mYyYKHTPr6Xy
- https://ipfs.status.im/QmeXp7FR7FSCKq2TVvXuhkqXbcsatZUM49JptuJXBrJ9zB
- https://ipfs.status.im/QmeYUhvW3WmVFcFynwUvMTjDg12WeeHU9PiLVGwLxy4oqK
- https://ipfs.status.im/Qmf52qvWGTFXm8BDAxWo9XuqfT9Lpa1L3fp3SaebBnyv5x
- https://ipfs.status.im/QmPJxKmckBKB5Yykw8GjHpnteC2t2xdt5VtK6Nm3K36ZZF
- https://ipfs.status.im/QmQ3aSpL2XUaunHQ2yqivUVRXzKHyeQTk7LHqZPGkmjCEo
- https://ipfs.status.im/QmQEtyC56XJxKc9c29F2Are1Htz3YN4oi4NKwPVzjHaDHu
- https://ipfs.status.im/QmQPbRfYvmvCFbDPFeAWALeiEsyoUKCELCn16XdXNCSpTd
- https://ipfs.status.im/QmQVMHbpFfirr1UyYeE5Fzv6gtomguFHsBiAMpz5gsM4Kx
- https://ipfs.status.im/QmQXFZdCFfFqgdBn5NNHKGqNxHjzrb6tYsrUWmrh752oSr
- https://ipfs.status.im/QmRbPVvsXWZqLLPhP4PJPLZiZ7TLFXYjwrFZQUJb61AjkY
- https://ipfs.status.im/QmRzGktYRK2PMPuvFDPyKg6Mnay1JCNmHp8BqDZkQuQHL9
- https://ipfs.status.im/QmSBvn378uVfVXhG9ThqLZUYfXg2USbjdG2FWSfsoFER9H
- https://ipfs.status.im/QmSdj3SV6HPjr8dC6Y3dFoHWhejHacTbAFtkcbA81BXjXA
- https://ipfs.status.im/QmSgrLon5WKEqnaHSuzUR1JQNFeZ6wQLjt1WsCbZ4dQ4Jb
- https://ipfs.status.im/QmSWhhE6GWep83pUhM92W6mNZdMH6M8gutjVcD9MDGeyXt
- https://ipfs.status.im/QmTaL29uiDp2vyroxUQNqAwFdnff3RYnavgoKEzQk33LRP
- https://ipfs.status.im/QmTVNzQh9cfE5gEdfFp2tZhTvQa2PaBpzoqxTncDQpackH
- https://ipfs.status.im/QmV2rcW76vy9GWYNtSfvvkf3fDiq4zHH1h72fxYUVUMBvT
- https://ipfs.status.im/QmV7iELRSYDTmtdkb8WB1XLGT2Bz1YbhqLCg7Mh7UMiXcs
- https://ipfs.status.im/QmVDCmbvoHzSNEMuyzhubGdKrpTccKELzeWS1XRQiPMk1b
- https://ipfs.status.im/QmViafYS4UBkE53JAW9S3g2B5Dfw7RoRYaj6TK5B1Bef8p
- https://ipfs.status.im/QmWkZd2uPTNsoe6ZRRpGDxHHKWpox7tEx3pqJNvVsAdF7W
- https://ipfs.status.im/QmWq3eEeRTFTk1oqyuvioUpa6GTZ9zF8w9qzvsyqxuKCuC
- https://ipfs.status.im/QmWrGR9NfKscKYxBfwg3R2ehajSaRs3u5MLTwc2c794JDU
- https://ipfs.status.im/QmZ6uh2Fqgc1WKGwsszmGVngXBm6dz6C5XwvUjeKMm4NUv
- https://ipfs.status.im/QmZMqVPmhXHM7TVHWiRcQc9E1WJ5PMKkvCkaVNabsG6Sq6
- https://ipfs.status.im/QmZnFa7rXpsfATbG9195qccj1UnmYEEnysu4wXVQ1phfky

**Comment by jakubgs** [comment]
Node to sefl, when using `$set` with `update()` in MongoDB don't do:
```js
db.x.update({QUERY}, {"$set":{"x":{"y":"value"}}})
```
Do:
```js
db.x.update({QUERY}, {"$set":{"x.y":"value"}})
```
Otherwise the whole contents of `x` key get reset to `{"y":"value"}` and all other keys are gone.

**Comment by jakubgs** [comment]
And did the same for prod:
```js
for (let hash in d) {
    let rval = db.dappsmetadatas.updateMany(
        {"details.image": "/metadata/image/"+hash},
        {"$set":{"details.image":"/metadata/image/"+d[hash]}}
    );
    print(rval.modifiedCount);
}
```
```js
for (let hash in d) {
    let rval = db.dappsimages.updateMany(
        {"hash": hash},
        {"$set":{"hash": d[hash]}}
    );
    print(rval.modifiedCount);
}
```

**Comment by jakubgs** [comment]
Here's the adjusted links on IPFS:
https://gist.github.com/jakubgs/d40e26ded70a96b3306489ccb8779bf3

I have also deployed the newly build prod version of the app to `prod-dap-ps-app`.
I consider this done.
