### ISSUE TITLE
Pin Dapp metedata from https://dap.ps/

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-ipfs#4]
I pinned images from https://dap.ps/ to our cluster in #2 but I forgot that I need to pin metadata.

I will need to fetch the data in the right format and try to upload it in exactly the same way.

Related to: https://github.com/dap-ps/discover/issues/42

**Comment by jakubgs** [comment]
Here's an example of a pinned Dapp metadata:
https://ipfs.status.im/QmZtKzVHDppsQCt8L2L3k9kFYn5MzHNu215DdRWNBxx5kc
Which is exactly the content of the `details` field in the doc from `dappsmetadatas` in MongoDB:
```
> db.dappsmetadatas.find({email:"my@addiction.io"}, { details: 1 })
{                 
  "_id" : ObjectId("5e331274aaf3707105995cf7"), 
  "details": {
    "name": "Addiction",
    "url": "https://addiction.io/",
    "description": "a",
    "category": "SOCIAL_NETWORKS",
    "image": "/metadata/image/QmeRLwvbUJtPQhnei2h5uYFD2BYtBamx3MkyHc9bdgZ9HW",
    "dateAdded": 1580405362566,
    "uploader": "0xeaf6C2193612AD5A9eDE45ea118CE9A24F408c6B"
  }
}
```

**Comment by jakubgs** [comment]
I tried this, but for some reason I'm getting a different hash:
```js
const fs = require('fs')
const fetch = require('node-fetch')
const ipfsClient = require('ipfs-http-client')

const main = async () => {
  const ipfs = ipfsClient(
      process.env.IPFS_HOST || 'ipfs.status.im',
      process.env.IPFS_PORT || 443,
      { protocol: 'https' }
  )

  let resp = await fetch('https://dev.dap.ps/metadata/all')
  let dapps = await resp.json()

  for (let [hash, dapp] of Object.entries(dapps)) {
    console.log(` * ${dapp.details.name}`)
    console.log(`   - OLD HASH: ${hash}`)

    let content = Buffer.from(JSON.stringify(dapp.details))
    resp = await ipfs.add(content, { pin: false })
    console.log(`   - NEW HASH: ${resp[0].hash}`)

    break
  }
}
```
```
 $ ./pin_metadata.js                                                                                                            ~/work/infra-utils/ipfs
 * Mobile Moving
   - OLD HASH: Qmf7qAjiruKxnErF33tVr9CVFDLGoPLR92bevpjos5RFdt
   - NEW HASH: QmSobeG8JjhKq1eYrJ9qpkboesRwWPdP2hgECbPLV2oD49
```
Even though I'm using the same method as `discover` repo, which is:
https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/back-end/services/ipfs-service.js#L25

**Comment by jakubgs** [comment]
Oh great, the image URL is different. The old metadata still used full URLs:
```
 $ curl -s https://ipfs.status.im/Qmf7qAjiruKxnErF33tVr9CVFDLGoPLR92bevpjos5RFdt | jq
{
  "name": "Mobile Moving",
  "url": "https://hard.life",
  "description": "Weekend tests on the go",
  "category": "SOCIAL_NETWORKS",
  "image": "https://dev.dap.ps/metadata/image/QmRRPqUyA8nAwx6PVf3c8MemQS2JNpgxBknaG11h7EXdNU",
  "dateAdded": 1565431027125,
  "uploader": "0x5f3371793285920351344a1eaaaa48d45e600652"
}
```
```
 $ curl -s https://ipfs.status.im/QmcnDy3LoKMuqj9ZtchL8UusJxWnSLSN2icPNXVpwGMaBx | jq
{
  "name": "Mobile Moving",
  "url": "https://hard.life",
  "description": "Weekend tests on the go",
  "category": "SOCIAL_NETWORKS",
  "image": "/metadata/image/Qmd6jv3UkdmKZ5DsSMfxdKekij6UfPYetrB9ng4ememx1g",
  "dateAdded": 1565431027125,
  "uploader": "0x5f3371793285920351344a1eaaaa48d45e600652"
}
```
Which means I either have to upload it as it was before, or change its hash, which will most definitely fuck with the contract. Is that correct @andytudhope ?

**Comment by jakubgs** [comment]
The simplest thing to do would be to just upload it as it used to be. But that might be a pain since we already updated the `details` in MongoDB, and some of them are gone from IPFS, so we don't know which form was used when.

**Comment by jakubgs** [comment]
It's possible to get previous values from our MongoDB backups, but that's not that easy to script.

**Comment by jakubgs** [comment]
And of course it's not just that image URLs are different, image HASHES are wrong too.
What a clusterfuck this software is.
![civilizaton](https://user-images.githubusercontent.com/2212681/73480315-f3f1f880-4399-11ea-954b-874a2c25cc8e.jpg)

**Comment by jakubgs** [comment]
I see 3 options:

* Upload the new `details` with new image URLs and hashes and update
  - This will possibly fuck up the contract, but I'm not sure
* Try to re-construct old Dapp `details` using MongoDB backups and upload that
  - A lot of awful fiddly work to get it working
* Say fuck it and leave it as it is
  - Probably not a solution

@andytudhope ?

**Comment by jakubgs** [comment]
I took a look at `contracts/Discover.sol` and it seems like a dapp in the contract doesn't actually use the IPFS hash:
```Solidity
    /**
     * @dev Anyone can create a DApp (i.e an arb piece of data this contract happens to care about).
     * @param _id bytes32 unique identifier.
     * @param _amount of tokens to stake on initial ranking.
     * @param _metadata metadata hex string
     */
    function createDApp(bytes32 _id, uint _amount, bytes32 _metadata) external {
        _createDApp(
            msg.sender,
            _id,
            _amount,
            _metadata);
    }
```
https://github.com/dap-ps/discover/blob/c72030cf/contracts/Discover.sol#L82-L94
```Solidity
    function _createDApp(
        address _from,
        bytes32 _id,
        uint _amount,
        bytes32 _metadata
        )
```
https://github.com/dap-ps/discover/blob/c72030cf/contracts/Discover.sol#L281-L286

It seems to me like none of the fields could contain an IPFS hash, and definitely not `bytes32`.
But I'm not 100% sure, someone who has experience with this contract would have to confirm.

**Comment by jakubgs** [comment]
This is the data structure for Dapps:
```Solidity
    // Whether we need more than an id param to identify arbitrary data must still be discussed.
    struct Data {
        address developer;
        bytes32 id;
        bytes32 metadata;
        uint balance;
        uint rate;
        uint available;
        uint votesMinted;
        uint votesCast;
        uint effectiveBalance;
    }
```
https://github.com/dap-ps/discover/blob/c72030cf/contracts/Discover.sol#L31-L42

I don't see how any of these fields could hold the IPFS hash. It might be okay to change them.

**Comment by jakubgs** [comment]
I've written a script to update the hashes and ran it on https://dev.dap.ps/:
https://github.com/status-im/infra-utils/blob/master/ipfs/pin_metadata.js
Here's the result Gist:
https://gist.github.com/jakubgs/68157ee262762f87e7af1108c76bd154
Now all the dapps in `dev` should have correct metadata IPFS hashes.

**Comment by jakubgs** [comment]
And it looks like that broke loading of highest ranked Dapps:
![broken_dev_dap_ps](https://user-images.githubusercontent.com/2212681/73530229-5b4e8d80-4418-11ea-9548-f73ce3836d34.png)
Lovely...

**Comment by jakubgs** [comment]
I have no fucking clue why. The `/metadata/all` call returns results just fine:
```
 $ curl -s https://dev.dap.ps/metadata/all | jq '.[].hash' | wc -l                                                                    ~/work/infra-utils/ipfs
46
```
Makes no sense. I'm getting breakfast.

**Comment by jakubgs** [comment]
I think I found out what happend. It looks like `sntValue` of Dapps is now `0` for all, which is why non show up in highest ranked. Specifically because of this sorting code:
```js
getHighestRanked() {
  if (this.dappsHightestRanked === null)
    this.dappsHightestRanked = this.dapps.filter(dapp => dapp.sntValue > 0)
  return this.dappsHightestRanked
}
```
https://github.com/dap-ps/discover/blob/c72030cf/src/common/data/dapp.js#L112-L116

From `dapps.filter(dapp => dapp.sntValue > 0)` we see that `dappsHightestRanked` will be empty.

**Comment by jakubgs** [comment]
But I have no clue whatsoever where `sntValue` comes from.

**Comment by jakubgs** [comment]
My hypothesis is that the `sntValue` is populated through the Infura calls like this one on `prod`:
![dap_ps_infura_call](https://user-images.githubusercontent.com/2212681/73537835-bf2d8200-4429-11ea-8cda-78f5fa192be3.png)

**Comment by jakubgs** [comment]
Adding a new dapp works just fine. So it's clearly something about me changing the hash:
![add_new_dapp_works](https://user-images.githubusercontent.com/2212681/73539225-30226900-442d-11ea-8290-9ea19b52bb96.png)

**Comment by jakubgs** [comment]
I think this is above my pay grade. I tried understanding where `sntValue` comes from but there's no clear place where it's being set. Maybe someone more familiar with Embark can help me.

**Comment by corpetty** [comment]
dapps are stored in a mapping of id -> Data.  Data is a struct:
```
struct Data {
        address developer;
        bytes32 id;
        bytes32 metadata;
        uint balance;
        uint rate;
        uint available;
        uint votesMinted;
        uint votesCast;
        uint effectiveBalance;
    }
```
and `effectiveBalance` is the `sntValue` in the application. Currently looking for where this id is generated.

**Comment by corpetty** [comment]
dappId is generated through a hash of metadata: https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/src/common/blockchain/services/discover-service/discover-service.js#L226

**Comment by corpetty** [comment]
hm... `bytes32 id` in the `Data struct` above is probably different than the `id` that is the key in the mapping.

**Comment by jakubgs** [comment]
This is where `createDApp()` is used:
https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/src/modules/Submit/Submit.reducer.js#L153-L164
And it includes `image`, which would have broken this when I updated image IPFS hashes, but it didn't, so the contract ID can't be derived from Dapp `details` from MongoDB.

**Comment by jakubgs** [comment]
Also, it appears to me that the:
```js
const dappId = web3.utils.keccak256(JSON.stringify(dappMetadata))
```
Happens only in `createDApp()`, which doesn't make sense if it's not stored in MongoDB, because then it would have to be re-created every time we query for `sntValue` or `effectiveBalance`.

It would also mean that editing Dapp metadata would be impossible without changing the ID in the contract, which makes for a horrible design.

**Comment by jakubgs** [comment]
Corey showed me that I can look at prod contract events events here:
https://etherscan.io/address/0x5bCF2767F86f14eDd82053bfBfd5069F68C2C5F8#events
And I looked through those and in my opinion we don't store Dapp IDs from the contract in MongoDB.
This is assuming that in events like `DAppCreated` the `topic1` field is the Dapp ID in the contract.

This would mean that the Dapp ID is derived from some other data. And based on this issue that data would have to include the `hash` field.

**Comment by corpetty** [comment]
correction of earlier Discover contract mapping of dapps... it does not map `id` to `Data`,  it maps `index` to `Data`, and the Data contains the `id` of the given dapp.

**Comment by jakubgs** [comment]
Corey found where the Frontends sets `compressedMetadata` in MongoDB to the Dapp ID:
```js
const initialDAppMetadata = await DAppMetadata.findOne({
  compressedMetadata: req.params.dappId,
})
```
https://github.com/dap-ps/discover/blob/c72030cfa7/back-end/controllers/dapps-metadata-controller.js#L64-L66

**Comment by jakubgs** [comment]
Just to verify that it was the `hash` change that caused this I reverted the `hash` change using:
```
> db.dappsmetadatas.updateOne(
    { hash: "QmSE2cvuA83UWqio5s8o8n8xkY2fruNrw2M3FzuSQiJXoh" },
    { $set: { hash: "QmbbbAFuG549so1X1pt4gabrKvygvN3jez8tdCtLq2hzQq" } }
)

{ "acknowledged" : true, "matchedCount" : 1, "modifiedCount" : 1 }
```
And the app is now visible again with 116 STT: https://dev.dap.ps/
![dapps_fixed_voting_dapp](https://user-images.githubusercontent.com/2212681/73673240-9bc73900-46ae-11ea-9b84-e9d1f957b3c9.png)

**Comment by jakubgs** [comment]
Okay, I had a theory that the issue was merging of `/matadata/all` response with Contract data so I made these changes:
```diff
--- a/src/common/blockchain/services/discover-service/discover-service.js
+++ b/src/common/blockchain/services/discover-service/discover-service.js
@@ -113,8 +113,16 @@ class DiscoverService extends BlockchainService {
       /* using Promise.all() to run calls in parallel */
       let dappsCalls = await Promise.all(asyncCalls)
 
+      console.dir(dappsCalls)
+      console.dir(dappsCache)
       for (let dapp of dappsCalls) {
+        console.log('Contract metadata field:')
+        console.dir(dapp.metadata)
         const dappMetadata = dappsCache[dapp.metadata]
+        console.log('Cache value for metadata:')
+        console.dir(dappMetadata)
         if (dappMetadata) {
           delete dappsCache[dapp.metadata]
           dapp.metadata = dappMetadata.details
```
And got some cool results:
```
Contract metadata field:
0x493d0325c390a6e38f3a6a7e838cf4a0b2e69c2f19be8831563f09bf8fba3aec
Cache value for metadata:
undefined
Contract metadata field:
0xbec550917904f7a5f2151e6267b7543a189b9524964e5f2ec7a929ffa4e24ac4
Cache value for metadata:
undefined
...
```
The `metadata` field that was being used from Contract was not matching anything in `dappsCache`.

And how is `dappsCache` populated? Here:
```js
const dappsCache = JSON.parse(
  JSON.stringify(await MetadataClient.retrieveMetadataCache()),
)
```
Which is implemented here:
```js

  static async retrieveAllDappsMetadata() {
    const retrievedDAppsMetadataResponse = await HTTPClient.getRequest(
      '/metadata/all'
    )

    const formatedDappsMetadata = {}
    const metadataHashes = Object.keys(retrievedDAppsMetadataResponse.data)
    for (let i = 0; i < metadataHashes.length; i++) {
      const convertedDappMetadataHash = helpers.getBytes32FromIpfsHash(
        metadataHashes[i],
      )

      formatedDappsMetadata[convertedDappMetadataHash] =
        retrievedDAppsMetadataResponse.data[metadataHashes[i]]
    }

    return formatedDappsMetadata
  }
```
https://github.com/dap-ps/discover/blob/c72030cf/src/common/clients/metadata-client.js#L63-L67

And the `helpers.getBytes32FromIpfsHash()` looks like this:
```js
export const getBytes32FromIpfsHash = ipfsListing => {
  const decodedHash = bs58
    .decode(ipfsListing)
    .slice(2)
    .toString('hex');
  return `0x${decodedHash}`;
};
```
https://github.com/dap-ps/discover/blob/c72030cf/src/common/utils/metadata-utils.js#L15-L21

**Comment by jakubgs** [comment]
This codebase is fucking retarded. There are as far as I can tell 3 implementations for getting Dapp ID:

---
#### [`src/common/blockchain/services/discover-service/discover-service.js`](https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/src/common/blockchain/services/discover-service/discover-service.js#L226)
```js
const dappId = web3.utils.keeccak256(JSON.stringify(dappMetadata))
```
#### [`src/common/clients/metadata-client.js`](https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/src/common/clients/metadata-client.js#L64-L66)
```js
const convertedDappMetadataHash = helpers.getBytes32FromIpfsHash(metadataHashes[i])
```
#### [`back-end/services/dapp-metadata-service.js`](https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/back-end/services/dapp-metadata-service.js#L20-L22)
```js
const compressedMetadata = web3Utils.keccak256(JSON.stringify(details.metadata))
```
---
None of this makes any fucking sense.

**Comment by jakubgs** [comment]
So it appears that helpers `getIpfsHashFromBytes32()` and `getBytes32FromIpfsHash()` are what conver the IPFS hash to a Contract `id` field of type `bytes32`. What I don't get is where does this happen when the Dapp is submitted.

**Comment by jakubgs** [comment]
I appears we have two options if we want to change the hashes:

1. Update the `metadata` field in the contract using [`setMetadata()`](https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/contracts/Discover.sol#L169-L180) method.
2. Use the unused [`ipfsHash`](https://github.com/dap-ps/discover/blob/c72030cfa7d3582c8efab651a532ba56b8a4b376/back-end/models/dapps-metadata-model.js#L65) field in MongoDB and store in it the legacy IPFS hash.

The first method is the simplest. The second one would require some kind of special case in JS.

**Comment by jakubgs** [comment]
Gist of Dapps, their contract IDs(`cm` or `compressedMetadata`) and old as well as new IPFS hashes:
https://gist.github.com/jakubgs/82ec4dde8687a565b1a5c16341c28660

**Comment by corpetty** [comment]
The first case above can only be done by the developer that submitted the dapp, so it would require a call to action from those that own each submission.

**Comment by jakubgs** [comment]
Precisely, so the only sensible fix we can do on our side is use the `ipfsHash` unused field.

It would be ugly, but at least we would keep compatibility for previously submitted dapps, and new ones would be fine, since their hash would be correct from the start.

**Comment by andytudhope** [comment]
Sorry to only be jumping into this now - have been moving house, hence my radio silence. It is indeed true that the IPFS hash is a _part_ of the `bytes32 metadata` stored in the contract, hence it breaking when you changed things.

It is also true that the client-side code checking for this and matching what is the contract, with what is in the DB, with what is in the cache is not good. I am sorry that you have had the pain of dealing with it. Nevertheless, I appreciate the effort here.

I agree that using the unused `ipfsHash` field is the best option, rather than asking everyone to update their metadata.

**Comment by jakubgs** [comment]
It appears I was wrong. `ipfsHash` appears to be used when app is approved:
```js
dappMetadata.ipfsHash = await IPFSService.addContent(json)
```
https://github.com/dap-ps/discover/blob/4a6256084abb1a25c295614792272bd9aeb96bc4/back-end/controllers/dapps-metadata-controller.js#L144-L145
It appears to me that the code is even more retarded than I though. It appears that `hash` is used when the app if first uploaded. And then when it is approved the `approveDApp()` method sets the `status` value to `APPROVED` and re-uploads it to IPFS, then settings `ipfsHash` with the new hash, rather than `hash`, which makes absolute zero fucking sense.

So I might have to add a separate field - `legacyHash` for example - and use that.
Or I could change it so it updates `hash` instead of `ipfsHash`, but that could break yet another thing...

**Comment by jakubgs** [comment]
Oh, I see, they don't change `hash` when the app is `APPROVED` because that would cause the same thing I caused. I might be able to fix this by setting `ipfsHash` to the new hash, and leaving `hash` as the original shitty hash to keep compatibility with the contract.

**Comment by jakubgs** [comment]
By using the following data: https://gist.github.com/jakubgs/82ec4dde8687a565b1a5c16341c28660
And this JS script in the MongoDB console for `dev` environment:
```js
for (let obj of data) {
    db.dappsmetadatas.updateOne(
        {hash: obj.new},
        {$set:{hash: obj.old, ipfsHash: obj.new}}
    )
}
```
I've restored `hash` to its old value and set `ipfsHash` to the new IPFS hash values.
This has recovered all the Dapps in the "Highest Ranked" section:
![dev_dap_ps_fixed_highest_ranked](https://user-images.githubusercontent.com/2212681/74334120-9ac29580-4d99-11ea-9298-bbd08a35804c.png)
This seems to be the simplest fix.

**Comment by jakubgs** [comment]
I've created a backup on Prod and I will attempt this IPFS hash fix on production:
```
admin@node-01.us-east-1a.db.prod:~ % sudo /var/lib/backups/prod_dap_ps_dump.sh      
2020-02-12T12:16:51.697+0000	dumping up to 3 collections in parallel
2020-02-12T12:16:51.697+0000	writing prod-dap-ps.dappsmetadatas to 
2020-02-12T12:16:51.697+0000	writing prod-dap-ps.dappsimages to 
2020-02-12T12:16:51.698+0000	writing prod-dap-ps.media to 
2020-02-12T12:16:51.755+0000	done dumping prod-dap-ps.dappsmetadatas (110 documents)
2020-02-12T12:16:51.755+0000	done dumping prod-dap-ps.media (78 documents)
2020-02-12T12:16:51.759+0000	done dumping prod-dap-ps.dappsimages (92 documents)
tar: Removing leading `/' from member names
admin@node-01.us-east-1a.db.prod:~ % ls -l /var/tmp/backups/mongodb/prod_dap_ps_dump_20200212121651.tar.gz
-rw-r--r-- 1 root root 1160694 Feb 12 12:16 /var/tmp/backups/mongodb/prod_dap_ps_dump_20200212121651.tar.gz
```

**Comment by jakubgs** [comment]
Here is the log of me running the [`pin_metadata.js`](https://github.com/status-im/infra-utils/blob/master/ipfs/pin_metadata.js) script:
https://gist.github.com/jakubgs/254fbf530d9398aeea42e3e198bcb135
And now the `ipfsHash` field is set for app Dapps in prod:
```sh
 $ curl -s https://raw.prod.dap.ps/metadata/all \
    | jq -r '. | values[] | .ipfsHash' \
    | xargs -n1 -I{} bash -c "curl -s 'https://ipfs.status.im/{}' | jq ."
{
  "name": "SNT Voting DApp",
  "url": "https://vote.status.im",
  "description": "Let your SNT be heard! Create your own poll or participate in quadratic voting.",
  "category": "UTILITIES",
  "image": "/metadata/image/QmV7iELRSYDTmtdkb8WB1XLGT2Bz1YbhqLCg7Mh7UMiXcs",
  "dateAdded": 1565873659515,
  "uploader": "0x5f3371793285920351344a1eaaaa48d45e600652"
}
{
  "name": "Livepeer",
  "url": "https://explorer.livepeer.org/",
  "description": "Decentralized video broadcasting",
  "category": "UTILITIES",
  "image": "/metadata/image/QmTuCSBso1n9gqRhCVsnPJdqeR4jzvHaAen2Jk81kqJXnJ",
  "dateAdded": 1565874722808,
  "uploader": "0x1d32f2acb832afc3d8c8ffb3be20e8dc7faac507"
}
{
  "name": "Civitas",
  "url": "https://communities.colu.com/",
  "description": "Blockchain-powered local communities",
  "category": "UTILITIES",
  "image": "/metadata/image/QmReWt4nKQtrTik4j7V53e4cDbDSR6y6bBb74pYri5xXpP",
  "dateAdded": 1565875167774,
  "uploader": "0x1d32f2acb832afc3d8c8ffb3be20e8dc7faac507"
}
...
```

**Comment by jakubgs** [comment]
Here's a PR for settings `ipfsHash` for newly created Dapps even if they were not approved yet:
https://github.com/dap-ps/discover/pull/76
This will make sure that `ipfsHash` is always set and never `null`.

**Comment by jakubgs** [comment]
Testing approval of new DApp in https://github.com/dap-ps/discover/pull/76 disproves my theory. The setting of `ipfsHash` in `approveDApp()` is absolutely pointless because `status` isn't stored under `details`, which is the part that gets re-uploaded to IPFS absolutely pointlessly. Fucking amazing.

**Comment by jakubgs** [comment]
Which means that this re-uploading does NOTHING:
https://github.com/dap-ps/discover/blob/4a6256084abb1a25c295614792272bd9aeb96bc4/back-end/controllers/dapps-metadata-controller.js#L142-L145

**Comment by jakubgs** [comment]
I call this done. From now on `ipfsHash` will always have the correct hash.
